services:
  ollama-server:
    # profiles: ["gpu-nvidia"]
    container_name: ollama-server
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    volumes:
      - ollama-model-cache:/root/.ollama
    restart: always
    networks:
      - ollama-demo
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-server-pull-deepseek
    volumes:
      - ollama-model-cache:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; OLLAMA_HOST=ollama-server:11434 ollama pull deepseek-r1:7b"
    networks:
      - ollama-demo

  openweb-ui:
    container_name: openweb-ui
    image: ghcr.io/open-webui/open-webui:main # ghcr.io/open-webui/open-webui:cuda for GPU support
    depends_on:
      - ollama-server
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
    volumes:
      - open-webui-data:/app/backend/data
    restart: always
    networks:
      - ollama-demo

volumes:
  ollama-model-cache:
  open-webui-data:

networks:
  ollama-demo: